package ociopleno;
// Generated 04-may-2017 0:42:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int ida;
     private Byte estado;
     private Date fecha;
     private String nombre;
     private String descripcion;
     private Integer edadMinima;
     private Integer edadMaxima;
     private Character sexo;
     private String lugar;
     private Set multimedias = new HashSet(0);
     private Set aficioneses = new HashSet(0);
     private Set participas = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(int ida) {
        this.ida = ida;
    }
    public Actividad(int ida, Byte estado, Date fecha, String nombre, String descripcion, Integer edadMinima, Integer edadMaxima, Character sexo, String lugar, Set multimedias, Set aficioneses, Set participas) {
       this.ida = ida;
       this.estado = estado;
       this.fecha = fecha;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.edadMinima = edadMinima;
       this.edadMaxima = edadMaxima;
       this.sexo = sexo;
       this.lugar = lugar;
       this.multimedias = multimedias;
       this.aficioneses = aficioneses;
       this.participas = participas;
    }
   
    public int getIda() {
        return this.ida;
    }
    
    public void setIda(int ida) {
        this.ida = ida;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(Integer edadMinima) {
        this.edadMinima = edadMinima;
    }
    public Integer getEdadMaxima() {
        return this.edadMaxima;
    }
    
    public void setEdadMaxima(Integer edadMaxima) {
        this.edadMaxima = edadMaxima;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getMultimedias() {
        return this.multimedias;
    }
    
    public void setMultimedias(Set multimedias) {
        this.multimedias = multimedias;
    }
    public Set getAficioneses() {
        return this.aficioneses;
    }
    
    public void setAficioneses(Set aficioneses) {
        this.aficioneses = aficioneses;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }




}


