package ociopleno;
// Generated 04-may-2017 0:42:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aficiones generated by hbm2java
 */
public class Aficiones  implements java.io.Serializable {


     private String aficiones;
     private Catalogo catalogo;
     private Set clientes = new HashSet(0);
     private Set actividads = new HashSet(0);

    public Aficiones() {
    }

	
    public Aficiones(String aficiones) {
        this.aficiones = aficiones;
    }
    public Aficiones(String aficiones, Catalogo catalogo, Set clientes, Set actividads) {
       this.aficiones = aficiones;
       this.catalogo = catalogo;
       this.clientes = clientes;
       this.actividads = actividads;
    }
   
    public String getAficiones() {
        return this.aficiones;
    }
    
    public void setAficiones(String aficiones) {
        this.aficiones = aficiones;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


