package ociopleno;
// Generated 04-may-2017 0:42:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catalogo generated by hbm2java
 */
public class Catalogo  implements java.io.Serializable {


     private String catalogo;
     private Set aficioneses = new HashSet(0);

    public Catalogo() {
    }

	
    public Catalogo(String catalogo) {
        this.catalogo = catalogo;
    }
    public Catalogo(String catalogo, Set aficioneses) {
       this.catalogo = catalogo;
       this.aficioneses = aficioneses;
    }
   
    public String getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(String catalogo) {
        this.catalogo = catalogo;
    }
    public Set getAficioneses() {
        return this.aficioneses;
    }
    
    public void setAficioneses(Set aficioneses) {
        this.aficioneses = aficioneses;
    }




}


