package ociopleno;
// Generated 04-may-2017 0:42:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idc;
     private String nick;
     private Date fnacimiento;
     private Character sexo;
     private String lugar;
     private String pass;
     private String email;
     private Set aficioneses = new HashSet(0);
     private Set participas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idc) {
        this.idc = idc;
    }
    public Cliente(int idc, String nick, Date fnacimiento, Character sexo, String lugar, String pass, String email, Set aficioneses, Set participas) {
       this.idc = idc;
       this.nick = nick;
       this.fnacimiento = fnacimiento;
       this.sexo = sexo;
       this.lugar = lugar;
       this.pass = pass;
       this.email = email;
       this.aficioneses = aficioneses;
       this.participas = participas;
    }
   
    public int getIdc() {
        return this.idc;
    }
    
    public void setIdc(int idc) {
        this.idc = idc;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public Date getFnacimiento() {
        return this.fnacimiento;
    }
    
    public void setFnacimiento(Date fnacimiento) {
        this.fnacimiento = fnacimiento;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getAficioneses() {
        return this.aficioneses;
    }
    
    public void setAficioneses(Set aficioneses) {
        this.aficioneses = aficioneses;
    }
    public Set getParticipas() {
        return this.participas;
    }
    
    public void setParticipas(Set participas) {
        this.participas = participas;
    }




}


