package ociopleno;
// Generated 04-may-2017 0:42:37 by Hibernate Tools 4.3.1



/**
 * Participa generated by hbm2java
 */
public class Participa  implements java.io.Serializable {


     private ParticipaId id;
     private Actividad actividad;
     private Cliente cliente;
     private Byte responsable;
     private Byte cumple;

    public Participa() {
    }

	
    public Participa(ParticipaId id, Actividad actividad, Cliente cliente) {
        this.id = id;
        this.actividad = actividad;
        this.cliente = cliente;
    }
    public Participa(ParticipaId id, Actividad actividad, Cliente cliente, Byte responsable, Byte cumple) {
       this.id = id;
       this.actividad = actividad;
       this.cliente = cliente;
       this.responsable = responsable;
       this.cumple = cumple;
    }
   
    public ParticipaId getId() {
        return this.id;
    }
    
    public void setId(ParticipaId id) {
        this.id = id;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Byte getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Byte responsable) {
        this.responsable = responsable;
    }
    public Byte getCumple() {
        return this.cumple;
    }
    
    public void setCumple(Byte cumple) {
        this.cumple = cumple;
    }




}


