/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ociopleno;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author jesus
 */
public class Principal extends javax.swing.JFrame {
    private Session sesion;
    private Cliente cliente;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        sesion=Login.getSesion();//Capturar sesion abierta
        cliente = Login.getCliente();//Capturar cliente logueado
        
        L_nick.setText("Usuario: "+ cliente.getNick()); // añade el nick a la label
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        B_verActividades = new javax.swing.JButton();
        B_nuevaActividad = new javax.swing.JButton();
        B_misActividades = new javax.swing.JButton();
        B_baja = new javax.swing.JButton();
        B_editar = new javax.swing.JButton();
        B_salir = new javax.swing.JButton();
        L_nick = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(384, 445));
        setResizable(false);

        B_verActividades.setText("Ver Actividades");
        B_verActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_verActividadesActionPerformed(evt);
            }
        });
        B_verActividades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_verActividadesKeyPressed(evt);
            }
        });

        B_nuevaActividad.setText("Nueva Actividad");
        B_nuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_nuevaActividadActionPerformed(evt);
            }
        });
        B_nuevaActividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_nuevaActividadKeyPressed(evt);
            }
        });

        B_misActividades.setText("Mis Actividades");
        B_misActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_misActividadesActionPerformed(evt);
            }
        });
        B_misActividades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_misActividadesKeyPressed(evt);
            }
        });

        B_baja.setText("Baja Voluntaria");
        B_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_bajaActionPerformed(evt);
            }
        });
        B_baja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_bajaKeyPressed(evt);
            }
        });

        B_editar.setText("Editar Perfil");
        B_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_editarActionPerformed(evt);
            }
        });
        B_editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_editarKeyPressed(evt);
            }
        });

        B_salir.setText("SALIR");
        B_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salirActionPerformed(evt);
            }
        });
        B_salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                B_salirKeyPressed(evt);
            }
        });

        L_nick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(L_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(B_misActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(B_baja, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(B_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_nuevaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_verActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {B_baja, B_editar, B_misActividades, B_nuevaActividad, B_salir, B_verActividades});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(L_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_verActividades)
                .addGap(32, 32, 32)
                .addComponent(B_nuevaActividad)
                .addGap(34, 34, 34)
                .addComponent(B_misActividades)
                .addGap(34, 34, 34)
                .addComponent(B_baja)
                .addGap(34, 34, 34)
                .addComponent(B_editar)
                .addGap(34, 34, 34)
                .addComponent(B_salir))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login vLogin = new Login(); // Crea una nueva ventana de Login
       vLogin.setLocationRelativeTo(null); // ventana centrada
       vLogin.setResizable(false);// No se puede cambiar el tamaño
       vLogin.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
       vLogin.setVisible(true);//visualiza la Ventana
        
    }//GEN-LAST:event_B_salirActionPerformed

    private void B_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_editarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Edicion   edicion = new Edicion();//crea la ventana Principal de Edición
        edicion.setLocationRelativeTo(null); // ventana centrada
        edicion.setResizable(false);// No se puede cambiar el tamaño
        edicion.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
        edicion.setVisible(true);//visualiza la Ventana
    }//GEN-LAST:event_B_editarActionPerformed

    private void B_editarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_editarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.dispose();
            Edicion edicion = new Edicion();//crea la ventana Principal de Edición
            edicion.setLocationRelativeTo(null); // ventana centrada
            edicion.setResizable(false);// No se puede cambiar el tamaño
            edicion.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
            edicion.setVisible(true);//visualiza la Ventana
        }
    }//GEN-LAST:event_B_editarKeyPressed

    private void B_salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_salirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.dispose();
            Login vLogin = new Login();
           vLogin.setLocationRelativeTo(null); // ventana centrada
           vLogin.setResizable(false);// No se puede cambiar el tamaño
           vLogin.setVisible(true);//visualiza la Ventana
        }
    }//GEN-LAST:event_B_salirKeyPressed

    private void B_nuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_nuevaActividadActionPerformed
        // TODO add your handling code here:
   
        
        NuevaActividad nuevaActividad = new NuevaActividad();
        nuevaActividad.setLocationRelativeTo(null); // ventana centrada
        nuevaActividad.setResizable(false);// No se puede cambiar el tamaño
        nuevaActividad.setDefaultCloseOperation(0);
        nuevaActividad.setVisible(true);//visualiza la Ventana
        
    }//GEN-LAST:event_B_nuevaActividadActionPerformed

    private void B_nuevaActividadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_nuevaActividadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            
            NuevaActividad nuevaActividad = new NuevaActividad();
            nuevaActividad.setLocationRelativeTo(null); // ventana centrada
            nuevaActividad.setResizable(false);// No se puede cambiar el tamaño
            nuevaActividad.setDefaultCloseOperation(0);
            nuevaActividad.setVisible(true);//visualiza la Ventana
            
        }
    }//GEN-LAST:event_B_nuevaActividadKeyPressed

    private void B_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_bajaActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que te quieres dar de baja?", null, JOptionPane.YES_NO_OPTION);
        if (opcion==0){
            Transaction tx = null;
              try{
                 tx = sesion.beginTransaction();
                 sesion.delete(cliente); 
                 tx.commit();
              }catch (HibernateException e) {
                 if (tx!=null) tx.rollback();
                 //e.printStackTrace(); 
                 JOptionPane.showMessageDialog(null,"Se ha producido un error: "+e);
              }
              this.dispose();
              // CREA UNA NUEVA VENTANA DE LOGIN
                Login vLogin = new Login();

               vLogin.setLocationRelativeTo(null); // ventana centrada
               vLogin.setResizable(false);// No se puede cambiar el tamaño
               vLogin.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
               vLogin.setVisible(true);//visualiza la Ventana
        }
    }//GEN-LAST:event_B_bajaActionPerformed

    private void B_bajaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_bajaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que te quieres dar de baja?", null, JOptionPane.YES_NO_OPTION);
            if (opcion==0){
                Transaction tx = null;
                try{
                    tx = sesion.beginTransaction();
                    sesion.delete(cliente); 
                    tx.commit();
                }catch (HibernateException e) {
                    if (tx!=null) tx.rollback();
                    //e.printStackTrace(); 
                    JOptionPane.showMessageDialog(null,"Se ha producido un error: "+e);
                }
                this.dispose();
                // CREA UNA NUEVA VENTANA DE LOGIN
                Login vLogin = new Login();

                vLogin.setLocationRelativeTo(null); // ventana centrada
                vLogin.setResizable(false);// No se puede cambiar el tamaño
                vLogin.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
                vLogin.setVisible(true);//visualiza la Ventanaa
            }
        }
    }//GEN-LAST:event_B_bajaKeyPressed

    private void B_verActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_verActividadesActionPerformed
      
        
        Actividades verActividad = new Actividades(this,true);
        verActividad.setLocationRelativeTo(null); // ventana centrada
        verActividad.setResizable(false);// No se puede cambiar el tamaño
        verActividad.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
        verActividad.setVisible(true);//visualiza la Ventana
        
    }//GEN-LAST:event_B_verActividadesActionPerformed

    private void B_verActividadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_verActividadesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(null,"Ventana de Ver Actividades");
       
        Actividades verActividad = new Actividades(this,true);
        verActividad.setLocationRelativeTo(null); // ventana centrada
        verActividad.setResizable(false);// No se puede cambiar el tamaño
        verActividad.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
        verActividad.setVisible(true);//visualiza la Ventana
        }
    }//GEN-LAST:event_B_verActividadesKeyPressed

    private void B_misActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_misActividadesActionPerformed
      
        
        Presidente misActividades = new Presidente(this,true);
        misActividades.setLocationRelativeTo(null); // ventana centrada
        misActividades.setResizable(false);// No se puede cambiar el tamaño
        misActividades.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
        misActividades.setVisible(true);//visualiza la Ventana
        
    }//GEN-LAST:event_B_misActividadesActionPerformed

    private void B_misActividadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_misActividadesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(null,"Ventana de Mis Actividades");
           
            Presidente misActividades = new Presidente(this,true);
            misActividades.setLocationRelativeTo(null); // ventana centrada
            misActividades.setResizable(false);// No se puede cambiar el tamaño
            misActividades.setDefaultCloseOperation(0);//Evita que se cierre la ventana con X
            misActividades.setVisible(true);//visualiza la Ventana
        
        }
    }//GEN-LAST:event_B_misActividadesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_baja;
    private javax.swing.JButton B_editar;
    private javax.swing.JButton B_misActividades;
    private javax.swing.JButton B_nuevaActividad;
    private javax.swing.JButton B_salir;
    private javax.swing.JButton B_verActividades;
    private javax.swing.JLabel L_nick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
