/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ociopleno;

import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import org.hibernate.Session;

/**
 *
 * @author profesor
 */
public class vistaTabla extends javax.swing.JPanel {
    String q="from Cliente";
    ResultSet consulta;
    List query; 
    Cliente c;
    Iterator cursor;

    /**
     * Creates new form vistaTabla
     */
    
     public vistaTabla() {
        //Nos conectamos a la base de datos
        Session sesion = NewHibernateUtil.getSessionFactory().openSession();
        org.hibernate.Transaction t=sesion.getTransaction();
        t.begin();            
          query=sesion.createQuery(q).list();
          cursor=query.iterator();
         
        TableModel dataModel = new AbstractTableModel() {
          public int getColumnCount() { return 2; }
          public int getRowCount() { return query.size();}
          public Object getValueAt(int row, int col) { return new Integer(row*col); }
      };
      jTableCliente = new JTable(dataModel);
      jScrollPane1= new JScrollPane(jTableCliente);
          while(cursor.hasNext()){
              
              c=(Cliente)cursor.next();
              Object [] fila = new Object[2];
                fila[0] = c.getNick();
                fila[1] = c.getPass();
                //dataModel.addRow ( fila ); // Añade una fila al final
                //modelo.setValueAt ("nuevo valor", 0, 1); // Cambia el valor de la fila 1, columna 2.
                //modelo.removeRow (0); // Borra la primera fila
             System.out.println(c.getNick()+" eureka "+c.getPass());
             
          }
   
        t.commit();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCliente);
        jTableCliente.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    // End of variables declaration//GEN-END:variables
}
